# -*- coding: utf-8 -*-
"""Corn_pest_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fplay_RLJo_1DdiskcvBI-bkM2Xvy28M
"""

from google.colab import drive
drive.mount('/content/drive')

# ==========================================================
# CORN PEST DETECTION SYSTEM
# EfficientNetB0 Transfer Learning + Fine Tuning
#
# Dataset Split:
# Training     : 70%
# Validation   : 15%
# Testing      : 15%
# ==========================================================


# ==========================================================
# IMPORT LIBRARIES
# ==========================================================
import os
import json
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras import layers
from tensorflow.keras import models

from tensorflow.keras.callbacks import (
    ModelCheckpoint,
    EarlyStopping,
    ReduceLROnPlateau,
    CSVLogger
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

# ==========================================================
# SETTINGS
# CHANGE THESE THREE PATHS to match where you put your

# ==========================================================
DATASET_PATH = "/content/drive/MyDrive/corn_pest/Train"
MODEL_FOLDER = "/content/drive/MyDrive/corn_pest/models"
RESULT_FOLDER = "/content/drive/MyDrive/corn_pest/results"

os.makedirs(MODEL_FOLDER, exist_ok=True)
os.makedirs(RESULT_FOLDER, exist_ok=True)

IMAGE_SIZE = 224

# Colab GPU (T4) can usually handle this comfortably.
# Drop to 16 if you hit an OOM error.
BATCH_SIZE = 32

# Training epochs
INITIAL_EPOCHS = 20

# Fine-tuning epochs
FINE_TUNE_EPOCHS = 15

SEED = 42

TRAIN_RATIO = 0.70
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15

# ==========================================================
# SYSTEM INFORMATION
# ==========================================================
print("\n")
print("="*80)
print("CORN PEST DETECTION SYSTEM")
print("EfficientNetB0 Transfer Learning + Fine Tuning")
print("="*80)
print("TensorFlow Version:", tf.__version__)
print("Available GPU:", tf.config.list_physical_devices("GPU"))

# ==========================================================
# CHECK DATASET
# ==========================================================
if not os.path.exists(DATASET_PATH):
    raise FileNotFoundError(
        f"Dataset not found: {DATASET_PATH}\n"
        "Make sure you uploaded your dataset to Google Drive and "
        "that DATASET_PATH above points to the folder containing "
        "one sub-folder per class."
    )

# ==========================================================
# LOAD DATASET
# ==========================================================
print("\nLoading Dataset...")

full_dataset = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    shuffle=True,
    seed=SEED
)

CLASS_NAMES = full_dataset.class_names
NUM_CLASSES = len(CLASS_NAMES)

print("\nDetected Classes")
print("-"*50)
for index, name in enumerate(CLASS_NAMES):
    print(index, ":", name)

# ==========================================================
# DATASET SPLIT
#
# 70% TRAIN
# 15% VALIDATION
# 15% TEST
# ==========================================================
dataset_size = tf.data.experimental.cardinality(full_dataset).numpy()

train_size = int(dataset_size * TRAIN_RATIO)
validation_size = int(dataset_size * VALIDATION_RATIO)

# test_size is the remainder so no batches are lost to rounding.
test_size = dataset_size - train_size - validation_size

expected_test_size = int(dataset_size * TEST_RATIO)
if abs(test_size - expected_test_size) > 1:
    print(
        f"\nWARNING: test_size ({test_size}) differs from "
        f"TEST_RATIO-based size ({expected_test_size}). "
        "Check that TRAIN_RATIO + VALIDATION_RATIO + TEST_RATIO == 1.0"
    )

print("\nDataset Distribution")
print("-"*50)
print("Training batches:", train_size)
print("Validation batches:", validation_size)
print("Testing batches:", test_size)

train_dataset = full_dataset.take(train_size)
remaining_dataset = full_dataset.skip(train_size)
validation_dataset = remaining_dataset.take(validation_size)
test_dataset = remaining_dataset.skip(validation_size)

# ==========================================================
# OPTIMIZE PIPELINE
# ==========================================================
AUTOTUNE = tf.data.AUTOTUNE

train_dataset = train_dataset.prefetch(AUTOTUNE)
validation_dataset = validation_dataset.prefetch(AUTOTUNE)
test_dataset = test_dataset.prefetch(AUTOTUNE)

# ==========================================================
# SAVE CLASS INFORMATION
# ==========================================================
class_path = os.path.join(MODEL_FOLDER, "class_names.json")

with open(class_path, "w", encoding="utf-8") as file:
    json.dump(CLASS_NAMES, file, indent=4)

print("\nClass names saved")
print(class_path)

# ==========================================================
# DATA AUGMENTATION
# ==========================================================
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.15),
    layers.RandomZoom(0.15),
    layers.RandomContrast(0.10)
], name="augmentation")

# ==========================================================
# LOAD EFFICIENTNETB0
# ==========================================================
print("\nLoading EfficientNetB0...")

base_model = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3)
)

# Freeze pretrained layers
base_model.trainable = False

# ==========================================================
# CREATE MODEL
# ==========================================================
inputs = layers.Input(shape=(IMAGE_SIZE, IMAGE_SIZE, 3))

x = data_augmentation(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(256, activation="relu")(x)
x = layers.Dropout(0.4)(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = models.Model(inputs, outputs, name="Corn_Pest_EfficientNetB0")

# ==========================================================
# COMPILE MODEL
# ==========================================================
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ==========================================================
# CALLBACKS
# ==========================================================
best_model_path = os.path.join(MODEL_FOLDER, "best_corn_pest_model.keras")

callbacks = [
    ModelCheckpoint(
        best_model_path,
        monitor="val_accuracy",
        save_best_only=True,
        mode="max",
        verbose=1
    ),
    EarlyStopping(
        monitor="val_loss",
        patience=6,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        verbose=1
    ),
    CSVLogger(os.path.join(RESULT_FOLDER, "training_history.csv"))
]

# ==========================================================
# STAGE 1 TRAINING
# TRAIN CLASSIFICATION HEAD
# ==========================================================
print("\n")
print("="*80)
print("STAGE 1 TRAINING")
print("Training Classification Layers")
print("="*80)

history_stage1 = model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=INITIAL_EPOCHS,
    callbacks=callbacks,
    verbose=1
)

# ==========================================================
# STAGE 2
# FINE TUNING EFFICIENTNETB0
# ==========================================================
print("\n")
print("="*80)
print("STAGE 2 FINE TUNING")
print("Unfreezing Last 30 Layers")
print("="*80)

# Enable base model training
base_model.trainable = True

# Freeze first layers
fine_tune_layers = 30

for layer in base_model.layers[:-fine_tune_layers]:
    layer.trainable = False

# Recompile with lower learning rate
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

history_stage2 = model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=(INITIAL_EPOCHS + FINE_TUNE_EPOCHS),
    initial_epoch=INITIAL_EPOCHS,
    callbacks=callbacks,
    verbose=1
)

# ==========================================================
# SAVE FINAL MODEL
# ==========================================================
final_model_path = os.path.join(MODEL_FOLDER, "final_corn_pest_model.keras")

model.save(final_model_path)

print("\n")
print("="*80)
print("MODEL SAVING COMPLETED")
print("="*80)
print("Best Model:")
print(best_model_path)
print("\nFinal Model:")
print(final_model_path)

# ==========================================================
# FINAL TESTING
# ==========================================================
print("\n")
print("="*80)
print("FINAL MODEL TESTING")
print("="*80)

# Load best saved model
best_model = tf.keras.models.load_model(best_model_path)

# ==========================================================
# TEST ACCURACY
# ==========================================================
test_loss, test_accuracy = best_model.evaluate(test_dataset, verbose=1)

print("\nTest Loss:")
print(test_loss)
print("\nTest Accuracy:")
print(f"{test_accuracy*100:.2f}%")

# ==========================================================
# COLLECT TEST LABELS + PREDICTIONS (single pass)
#
# test_dataset was built with shuffle=True, which reshuffles
# on every new iteration. Iterating it separately for labels
# and then again for predict() would give two DIFFERENT
# orderings, so both are done in one loop to keep them aligned.
# ==========================================================
print("\nPredicting Test Images...")

true_labels = []
predicted_labels = []

for images, labels in test_dataset:
    batch_predictions = best_model.predict(images, verbose=0)

    true_labels.extend(np.argmax(labels.numpy(), axis=1))
    predicted_labels.extend(np.argmax(batch_predictions, axis=1))

true_labels = np.array(true_labels)
predicted_labels = np.array(predicted_labels)

# ==========================================================
# PERFORMANCE METRICS
# ==========================================================
final_accuracy = np.mean(true_labels == predicted_labels)

precision = precision_score(
    true_labels, predicted_labels, average="weighted", zero_division=0
)

recall = recall_score(
    true_labels, predicted_labels, average="weighted", zero_division=0
)

f1 = f1_score(
    true_labels, predicted_labels, average="weighted", zero_division=0
)

print("\n")
print("="*80)
print("FINAL TEST PERFORMANCE")
print("="*80)
print(f"Accuracy  : {final_accuracy*100:.2f}%")
print(f"Precision : {precision*100:.2f}%")
print(f"Recall    : {recall*100:.2f}%")
print(f"F1 Score  : {f1*100:.2f}%")

# ==========================================================
# CLASSIFICATION REPORT
# ==========================================================
class_report = classification_report(
    true_labels,
    predicted_labels,
    target_names=CLASS_NAMES,
    digits=4,
    zero_division=0
)

print("\n")
print(class_report)

# ==========================================================
# CONFUSION MATRIX
# ==========================================================
confusion = confusion_matrix(true_labels, predicted_labels)

print("\nConfusion Matrix")
print(confusion)

# ==========================================================
# SAVE TEST REPORT
# ==========================================================
report_file = os.path.join(RESULT_FOLDER, "accuracy_report.txt")

with open(report_file, "w", encoding="utf-8") as file:
    file.write("="*80)
    file.write("\nCORN PEST DETECTION MODEL REPORT\n")
    file.write("="*80)

    file.write("\n\nMODEL INFORMATION\n")
    file.write("-"*80)
    file.write("\nModel : EfficientNetB0")
    file.write("\nTransfer Learning + Fine Tuning")
    file.write("\nImage Size : 224 x 224")
    file.write("\nClasses : " + str(NUM_CLASSES))

    file.write("\n\nDATASET SPLIT\n")
    file.write("-"*80)
    file.write("\nTraining : 70%")
    file.write("\nValidation : 15%")
    file.write("\nTesting : 15%")

    file.write("\n\nFINAL TEST RESULTS\n")
    file.write("-"*80)
    file.write(f"\nTest Loss : {test_loss:.6f}")
    file.write(f"\nAccuracy : {final_accuracy*100:.2f}%")
    file.write(f"\nPrecision : {precision*100:.2f}%")
    file.write(f"\nRecall : {recall*100:.2f}%")
    file.write(f"\nF1 Score : {f1*100:.2f}%")

    file.write("\n\nCLASSIFICATION REPORT\n")
    file.write("="*80)
    file.write("\n")
    file.write(class_report)

    file.write("\n\nCONFUSION MATRIX\n")
    file.write("="*80)
    file.write("\n")
    file.write(np.array2string(confusion, separator=", "))

print("\nReport Saved:")
print(report_file)

# ==========================================================
# TRAINING GRAPH DATA
# ==========================================================
train_accuracy = history_stage1.history["accuracy"] + history_stage2.history["accuracy"]
validation_accuracy = history_stage1.history["val_accuracy"] + history_stage2.history["val_accuracy"]
train_loss = history_stage1.history["loss"] + history_stage2.history["loss"]
validation_loss = history_stage1.history["val_loss"] + history_stage2.history["val_loss"]

epochs = range(1, len(train_accuracy) + 1)

# ==========================================================
# ACCURACY GRAPH
# ==========================================================
plt.figure(figsize=(10, 6))
plt.plot(epochs, train_accuracy, label="Training Accuracy")
plt.plot(epochs, validation_accuracy, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Corn Pest Detection Accuracy")
plt.legend()
plt.grid(True)
plt.tight_layout()

accuracy_graph = os.path.join(RESULT_FOLDER, "accuracy_graph.png")
plt.savefig(accuracy_graph, dpi=300)
plt.show()
plt.close()

# ==========================================================
# LOSS GRAPH
# ==========================================================
plt.figure(figsize=(10, 6))
plt.plot(epochs, train_loss, label="Training Loss")
plt.plot(epochs, validation_loss, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Corn Pest Detection Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()

loss_graph = os.path.join(RESULT_FOLDER, "loss_graph.png")
plt.savefig(loss_graph, dpi=300)
plt.show()
plt.close()

# ==========================================================
# FINAL SUMMARY
# ==========================================================
summary_file = os.path.join(RESULT_FOLDER, "training_summary.txt")

with open(summary_file, "w", encoding="utf-8") as file:
    file.write("CORN PEST DETECTION FINAL SUMMARY\n")
    file.write("="*80)
    file.write(f"\n\nFinal Accuracy : {final_accuracy*100:.2f}%")
    file.write(f"\nPrecision : {precision*100:.2f}%")
    file.write(f"\nRecall : {recall*100:.2f}%")
    file.write(f"\nF1 Score : {f1*100:.2f}%")

print("\n")
print("="*80)
print("TRAINING PIPELINE COMPLETED SUCCESSFULLY")
print("="*80)
print("\nGenerated Files:")
print("\nBest Model:")
print(best_model_path)
print("\nFinal Model:")
print(final_model_path)
print("\nAccuracy Report:")
print(report_file)
print("\nAccuracy Graph:")
print(accuracy_graph)
print("\nLoss Graph:")
print(loss_graph)
print("\nModel Ready for Corn Pest Detection")

# ==========================================================
# CORN PEST DETECTION - PREDICT A SINGLE NEW IMAGE

# Loads the already-trained best model and predicts the
# pest class for one new photo. No training involved.
# ==========================================================

import os
import json
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# ==========================================================
# SETTINGS
# ==========================================================
MODEL_FOLDER = "/content/drive/MyDrive/corn_pest/models"
IMAGE_SIZE = 224

best_model_path = os.path.join(MODEL_FOLDER, "best_corn_pest_model.keras")
class_names_path = os.path.join(MODEL_FOLDER, "class_names.json")

# ==========================================================
# GET THE TEST IMAGE
# ==========================================================
from google.colab import files

print("Please choose an image file to upload...")
uploaded = files.upload()

# Grab the first (and normally only) uploaded file
IMAGE_PATH = "/content/drive/MyDrive/corn_pest/test_photo.jpg" + list(uploaded.keys())[0]

# ==========================================================
# CHECK MODEL + IMAGE EXIST
# ==========================================================
if not os.path.exists(best_model_path):
    raise FileNotFoundError(
        f"Model not found: {best_model_path}\n"
        "Make sure you already ran the training script and that "
        "MODEL_FOLDER above matches the training script's MODEL_FOLDER."
    )

if not os.path.exists(IMAGE_PATH):
    raise FileNotFoundError(f"Image not found: {IMAGE_PATH}")

# ==========================================================
# LOAD MODEL + CLASS NAMES
# ==========================================================
print("\nLoading model...")
model = tf.keras.models.load_model(best_model_path)

with open(class_names_path, "r", encoding="utf-8") as file:
    CLASS_NAMES = json.load(file)

# ==========================================================
# LOAD + PREPROCESS THE IMAGE
# ==========================================================
img = tf.keras.utils.load_img(
    IMAGE_PATH,
    target_size=(IMAGE_SIZE, IMAGE_SIZE)
)

img_array = tf.keras.utils.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # shape: (1, 224, 224, 3)

# ==========================================================
# PREDICT
# ==========================================================
predictions = model.predict(img_array, verbose=0)
probabilities = predictions[0]

predicted_index = np.argmax(probabilities)
predicted_class = CLASS_NAMES[predicted_index]
confidence = probabilities[predicted_index] * 100

# ==========================================================
# SHOW THE IMAGE
# ==========================================================
plt.figure(figsize=(5, 5))
plt.imshow(mpimg.imread(IMAGE_PATH))
plt.axis("off")
plt.title(f"{predicted_class} ({confidence:.2f}%)")
plt.show()

# ==========================================================
# SHOW RESULT
# ==========================================================
print("\n" + "="*60)
print("PREDICTION RESULT")
print("="*60)
print(f"Image        : {IMAGE_PATH}")
print(f"Predicted    : {predicted_class}")
print(f"Confidence   : {confidence:.2f}%")

print("\nAll class probabilities:")
print("-"*60)
sorted_indices = np.argsort(probabilities)[::-1]
for i in sorted_indices:
    print(f"{CLASS_NAMES[i]:40s} : {probabilities[i]*100:.2f}%")